name: "GitHub Action for Firebase"
author: "Jeremy Shore"
description: "Wraps the firebase-tools CLI to enable common commands."
branding:
  icon: "package"
  color: "gray-dark"
outputs:
  output:
    description: "The output of the executed command"
runs:
  using: "docker"
  image: "Dockerfile"
